import { Box } from "@chakra-ui/react";
import Head from "next/head";
import About from "../components/homepage/AboutHim";
import CampaignFeat from "../components/homepage/CampaignFeat";
import Hero from "../components/homepage/Hero";
import SupportGroups from "../components/homepage/SupportGroups";
import Vision from "../components/homepage/Vision";

export default function Home() {
  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <CampaignFeat />
      <About />
      <Vision />
      <SupportGroups />
    </Box>
  );
}
